### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nobananasforyou** [Asd-g/AviSynth-SmoothUV2#1]
Hello,

Thanks for porting this to avs. I was testing it on a source and it resulted in a green bar on the right hand side. Changing the threshold value from 200+ changes the color of the bar on the right hand side. For example, SmoothUV(radius=1, threshold=200) (Yellow), SmoothUV(radius=1, threshold=220) (Cyan and Yellow), and so on. Also, note that setting the threshold value to 100 still nukes the red color really hard (take a look at the hat). Here's an image comparison for illustration: https://slow.pics/c/LGe8F7tb

Script:
src()
SmoothUV(radius=1) 

Kind Regards

**Comment by Asd-g** [comment]
Please try version 3.0.0.

**Comment by nobananasforyou** [comment]
Thanks. I did test it out. Calling SmoothUV(radius=1) is resulting in color bleeding. Here's an image comparison: https://slow.pics/c/ClGBGdpx

**Comment by Asd-g** [comment]
You can try 3.0.1.

**Comment by nobananasforyou** [comment]
Still the same. There are no differences.

**Comment by Asd-g** [comment]
So the latest columns are fine (right hand side)?

That color bleeding is result of the high threshold. For default radius threshold=50 should be fine. It's recommended to use lower threshold for lower radius.
This filter should be used with some edge mask. Did you try [rainbow_smooth](https://github.com/Asd-g/AviSynthPlus-Scripts/blob/master/Rainbow_smooth_.avsi)? It's smoothuv + edge mask.

**Comment by realfinder** [comment]
maybe function name should be changed since now it's not match with old one
since its SmoothUV2 so the function name should be that too

**Comment by Asd-g** [comment]
There was plane shifting (vertical for interlaced frames and horizontal) that was the culprit for that severe chroma bleeding.

Function name changed to SmoothUV2.

**Comment by kedaitinh12** [comment]
Folder MSVC still info ver 3.0.0

**Comment by kedaitinh12** [comment]
And i seen mistake: update "ot" ver 4.0.0

**Comment by Asd-g** [comment]
> 
> 
> Folder MSVC still info ver 3.0.0

Because there is no change of the files there between 3.0.0 and 4.0.0.

**Comment by nobananasforyou** [comment]
There's still slight color bleeding around the edges but it's very minuscule. Upon further inspection, color bleeding occurs on the inside. SmoothUV doesn't seem to effect the green color at all but only Blue and Red. It would be wonderful if you could figure out why both blue and red are being nuked so heavily.

Image Comparison:
https://slow.pics/c/Hg50q9AS

**Comment by Asd-g** [comment]
I wrote that default threshold is relatively high and some mask is recommended to be used. [Here](https://imgaa.com/gallery/LAGFbVJ4r3569EI) smootuv2(radius=2, threshold=20) vs smoothuv2(radius=1) vs rainbow_smooth(radius=2).
> 
> 
> SmoothUV doesn't seem to effect the green color at all but only Blue and Red.

It's how the colors are saved in YUV format ( https://www.baslerweb.com/fp-1485687431/media/editorial/content_images/faqs/faq_yuv_2.png ).

**Comment by nobananasforyou** [comment]
Okay.

**Comment by Asd-g** [comment]
> SmoothUV doesn't seem to effect the green color at all but only Blue and Red. It would be wonderful if you could figure out why both blue and red are being nuked so heavily.

@nobananasforyou, you can try the new version (a little bit more precise calculations for 8-bit). If you can use the filter in 16-bit, it's recommended.

**Comment by kedaitinh12** [comment]
Thanks
