### ISSUE TITLE
Color Retention

### ISSUE THREAD

**Issue by nobananasforyou** [Asd-g/AviSynth-SmoothUV2#3]
Hello

I tested SmoothUV2 on a source and found that the color green was being nuked harder than the red. There is some blurring but the green color just becomes white. I was wondering if there was a way to retain some color accuracy. I do understand that color degradation is the byproduct of derainbowing. Example: https://slow.pics/c/nd9Ey3q4

Dubhater's port has color accuracy but contains the bugs you fixed in your port: https://github.com/dubhater/vapoursynth-smoothuv/issues/2

Kind Regards

**Comment by dubhater** [comment]
What is the reason for the shift left by 8? I don't understand it:
https://github.com/Asd-g/AviSynth-SmoothUV2/blob/36415a36f8323ce8485b7b17722e6cc6c4197da5/src/SmoothUV2.cpp#L34

**Comment by Asd-g** [comment]
> What is the reason for the shift left by 8? I don't understand it:
> 
> https://github.com/Asd-g/AviSynth-SmoothUV2/blob/36415a36f8323ce8485b7b17722e6cc6c4197da5/src/SmoothUV2.cpp#L34

No reason. It's probably left from the debugging process.

@nobananasforyou, currently you can't compare directly the vs (chroma shift) and this version - https://slow.pics/c/GR9txBBr (zoom to see the shift). If you want less nuked colors try lower threshold.

Edit: try `dither=1`

**Comment by nobananasforyou** [comment]
AVS:
SmoothUV2(radius=1, threshold=10)
SmoothUV2(radius=1, threshold=50)

VS:
SmoothUV2(radius=1, threshold=225)

Comparatively, the colors are being nuked in your port even with the lower values. I just tested with the parameter dither=1 as you suggested but there is not much improvement.

**Comment by Asd-g** [comment]
Can you show what you mean by nuked in your example from the first post ( https://slow.pics/c/nd9Ey3q4 )?

**Comment by nobananasforyou** [comment]
I think nuke is the wrong word, maybe discoloration. Take a look at the leaf's vascular tissue and stem. The color green becomes less vibrant but if you think I'm exaggerating you can close this thread.
